---
- name: install httpd
  yum:
    name:
      - httpd
      - firewalld
    state: present

- name: start and enabled httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: start and enabled firewalld
  service: 
    name: firewalld
    state: started
    enabled: true

- name: create the index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: add http service into firewalls
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: yes


    
